server:
  servlet:
    context-path: /dev-api

  error:
    include-message: always
    include-stacktrace: always
    include-exception: true

spring:
  application:
    name: ShoppingLists - Development

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: debug
        security: info
